#!/usr/bin/env bash
set -euo pipefail

# script was generated by AI!

# -----------------------------
# CONFIG
# -----------------------------

ARCHIVE=true           # default: always archive
ARCHIVE_ROOT="ci/archive"
IGNORE=()              # branches to ignore

# -----------------------------
# HELPERS
# -----------------------------
print_usage() {
    echo "Usage: [--no-archive] [branches to ignore...]"
}

timestamp() {
    date +"%Y%m%d-%H%M%S"
}

# -----------------------------
# ARGUMENT PARSING
# -----------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-archive)
            ARCHIVE=false
            shift
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            IGNORE+=("$1")
            shift
            ;;
    esac
done

# -----------------------------
# FETCH REMOTES
# -----------------------------
git fetch --prune

REMOTE_BRANCHES=$(git branch -r | sed 's/^[[:space:]]*//' | grep -v 'origin/HEAD')

# -----------------------------
# NORMALIZE IGNORE LIST
# -----------------------------
NORMALIZED_IGNORE=()
for b in "${IGNORE[@]}"; do
    NORMALIZED_IGNORE+=("origin/$b")
done

# -----------------------------
# FILTER BRANCHES TO DELETE
# -----------------------------
BRANCHES_TO_DELETE=()
while read -r branch; do
    skip=false
    for ig in "${NORMALIZED_IGNORE[@]}"; do
        if [[ "$branch" == "$ig" ]]; then
            skip=true
            break
        fi
    done

    if [[ "$skip" == false ]]; then
        BRANCHES_TO_DELETE+=("$branch")
    fi
done <<< "$REMOTE_BRANCHES"

# -----------------------------
# SETUP ARCHIVE FOLDER
# -----------------------------
if $ARCHIVE; then
    TOP_DIR=$(git rev-parse --show-toplevel)
    ARCHIVE_DIR="$TOP_DIR/$ARCHIVE_ROOT/$(timestamp)"
    mkdir -p "$ARCHIVE_DIR"
    echo "Archiving snapshots to $ARCHIVE_DIR"
fi

# -----------------------------
# SHOW SUMMARY
# -----------------------------
echo "Will delete these remote branches:"
printf "  %s\n" "${BRANCHES_TO_DELETE[@]}"

if [[ ${#BRANCHES_TO_DELETE[@]} -eq 0 ]]; then
    echo "Nothing to delete. Exiting."
    exit 0
fi

# -----------------------------
# CONFIRMATION
# -----------------------------
read -r -p "Type 'yes' to confirm: " CONFIRM
if [[ "$CONFIRM" != "yes" ]]; then
    echo "Aborted."
    exit 1
fi

# -----------------------------
# DELETE WITH OPTIONAL ARCHIVE
# -----------------------------
echo "Processing branches..."
for branch in "${BRANCHES_TO_DELETE[@]}"; do
    short=${branch#origin/}

    if $ARCHIVE; then
        archive_file="$ARCHIVE_DIR/$short.tar"
        # create a tar snapshot of the branch
        git archive --format=tar -o "$archive_file" "$branch" 2>/dev/null || {
            echo "Failed to archive $branch (ignored)"
        }
    fi

    # delete remote branch (ignore failures)
    if git push origin --delete "$short" 2>/dev/null; then
        echo "Deleted: $branch"
    else
        echo "Failed:  $branch (ignored)"
    fi
done

echo "Done."
